services:
  - type: web
    name: chess-tutor-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: oregon
    plan: free
    envVars:
      - key: CORS_ORIGINS
        value: https://bgitig.github.io
